'use client';

import { Sparkles, Clock, Bot } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';

interface AISeasonReviewProps {
  review: string;
  generatedAt: string | null;
  model: string | null;
  year: number;
}

export function AISeasonReview({ review, generatedAt, model, year }: AISeasonReviewProps) {
  const formattedDate = generatedAt
    ? new Date(generatedAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : null;

  return (
    <Card className="relative overflow-hidden">
      {/* Subtle AI sparkle background */}
      <div className="absolute right-4 top-4 opacity-5">
        <Sparkles className="h-32 w-32 text-primary" />
      </div>

      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Sparkles className="h-5 w-5 text-primary" />
          {year} Season Review
        </CardTitle>
        <div className="flex items-center gap-4 text-xs text-muted-foreground">
          <span className="flex items-center gap-1">
            <Bot className="h-3 w-3" />
            AI Generated
          </span>
          {formattedDate && (
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formattedDate}
            </span>
          )}
        </div>
      </CardHeader>

      <CardContent className="relative">
        <div
          className={cn(
            'prose prose-sm prose-invert max-w-none',
            'prose-p:text-muted-foreground prose-p:leading-relaxed',
            'prose-strong:text-foreground prose-strong:font-semibold',
            'prose-headings:text-foreground'
          )}
        >
          {/* Render review as paragraphs */}
          {review.split('\n\n').map((paragraph, index) => {
            // Check if it's a header (starts with # or **)
            const isHeader = paragraph.startsWith('#') || paragraph.startsWith('**');

            if (isHeader) {
              // Remove markdown formatting and render as bold
              const text = paragraph.replace(/^#+\s*/, '').replace(/\*\*/g, '');
              return (
                <p key={index} className="font-semibold text-foreground mt-4 first:mt-0">
                  {text}
                </p>
              );
            }

            return (
              <p key={index} className="mb-4 last:mb-0">
                {paragraph}
              </p>
            );
          })}
        </div>

        {/* Model info footer */}
        {model && (
          <div className="mt-6 pt-4 border-t border-border/50">
            <p className="text-xs text-muted-foreground/60 font-mono">
              Generated by {model}
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

/**
 * Empty state when no AI review exists
 */
export function AISeasonReviewEmpty({ year }: { year: number }) {
  return (
    <Card className="relative overflow-hidden">
      <CardContent className="py-12 text-center">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-muted-foreground/30" />
        <p className="text-muted-foreground">
          No AI review available for the {year} season yet.
        </p>
      </CardContent>
    </Card>
  );
}
